export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_QTY = "UPDATE_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR";
